# Generated by Django 4.1 on 2022-08-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_point_remove_profile_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='AppDownload',
        ),
        migrations.AddField(
            model_name='task',
            name='Appname',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Point',
            field=models.IntegerField(default=0),
        ),
    ]
