# Generated by Django 4.1 on 2022-08-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_task_appdownload_task_appname_task_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Appname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
