# Generated by Django 4.1 on 2022-08-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_task_appname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='AppId',
            field=models.IntegerField(default=0),
        ),
    ]
